-- Phase 6A: the hosted platform authority tables.
--
-- This is a faithful PostgreSQL port of the SQLite ``platform_*`` schema that
-- lives under ``src/cre_mcp/platform/``. It exists so the hosted process can
-- boot on PostgreSQL without carrying a second, divergent definition of who a
-- user is, which workspace they belong to, which OAuth session speaks for
-- them, and which provider receipt granted them access. Every table, index,
-- constraint and trigger below was captured by building the SQLite schema in
-- an in-memory database (schema.SCHEMA + platform-core + admin-controls +
-- oauth + entitlements + provider-sync migrations, plus the connection.py
-- tables) and dumping ``sqlite_master``, so the f-string-interpolated CHECK
-- choice lists are the resolved literals rather than a hand transcription.
--
-- Type mapping: INTEGER -> bigint, REAL -> double precision, TEXT -> text.
-- ``INTEGER PRIMARY KEY AUTOINCREMENT`` becomes
-- ``bigint GENERATED BY DEFAULT AS IDENTITY`` — BY DEFAULT, not ALWAYS, so an
-- explicit id can still be supplied exactly as SQLite allows. Columns that
-- hold 0/1 flags stay numeric ``bigint`` with their ``CHECK(x IN (0,1))``:
-- the Python stores write and compare integers, and turning them into
-- ``boolean`` would silently change every comparison in the store code.
--
-- NO ROW-LEVEL SECURITY ON ANY TABLE BELOW — deliberately.
-- These stores are the identity and authority layer. They run BEFORE a
-- workspace context exists: resolving a browser session to a user, exchanging
-- an authorization code, deciding which workspace a provider receipt even
-- belongs to. There is no ``app.workspace_id`` to filter on at that point, so
-- an RLS policy here would either be a no-op or would lock the authority layer
-- out of its own bootstrap. Tenancy on these tables is enforced in the store
-- code exactly as it was under SQLite, and the grant boundary below is the
-- database-side control. The certified ``medawarcre.*`` tenant tables from
-- migrations 0001-0009 keep their RLS unchanged; nothing here touches them.

-- ---------------------------------------------------------------------------
-- Migration bookkeeping for the SQLite-side runner
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/migrations.py:24
CREATE TABLE IF NOT EXISTS medawarcre.platform_schema_versions (
    component text NOT NULL,
    version bigint NOT NULL,
    description text NOT NULL,
    applied_at text NOT NULL,
    PRIMARY KEY(component, version)
);

-- ---------------------------------------------------------------------------
-- Core platform schema (src/cre_mcp/platform/schema.py, SCHEMA template)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS medawarcre.platform_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    name text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS medawarcre.platform_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL UNIQUE,
    name text NOT NULL,
    monthly_price_usd double precision,
    seat_limit bigint,
    -- platform-core migration 1 ("server-owned daily plan quotas") adds
    -- daily_quotas; the template already carries it on a fresh database.
    daily_quotas text NOT NULL DEFAULT '{}',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK(monthly_price_usd IS NULL OR monthly_price_usd >= 0),
    CHECK(seat_limit IS NULL OR seat_limit > 0)
);

CREATE TABLE IF NOT EXISTS medawarcre.platform_workspaces (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id text NOT NULL UNIQUE,
    name text NOT NULL,
    slug text UNIQUE,
    plan_id bigint,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(plan_id) REFERENCES medawarcre.platform_plans(id)
);

CREATE TABLE IF NOT EXISTS medawarcre.platform_memberships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(workspace_id, user_id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    CHECK(role IN ('owner', 'admin', 'member', 'viewer'))
);

CREATE INDEX IF NOT EXISTS idx_platform_memberships_workspace
    ON medawarcre.platform_memberships(workspace_id, created_at);

CREATE TABLE IF NOT EXISTS medawarcre.platform_territories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    name text NOT NULL,
    state text,
    market text,
    asset_type text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(workspace_id, name),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_platform_territories_workspace
    ON medawarcre.platform_territories(workspace_id, created_at);

CREATE TABLE IF NOT EXISTS medawarcre.platform_connected_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    name text NOT NULL,
    client_type text NOT NULL,
    scopes text NOT NULL DEFAULT '[]',
    status text NOT NULL DEFAULT 'active',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(status IN ('active', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_platform_connected_clients_workspace
    ON medawarcre.platform_connected_clients(workspace_id, created_at);

-- UNIQUE(workspace_id, id) is not decorative: platform_notes and
-- platform_outcomes carry composite foreign keys onto (workspace_id, id), and
-- PostgreSQL requires a matching unique constraint on the parent for those.
CREATE TABLE IF NOT EXISTS medawarcre.platform_saved_deals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    deal_ref text NOT NULL,
    title text NOT NULL,
    payload text NOT NULL DEFAULT '{}',
    stage text NOT NULL DEFAULT 'watching',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(workspace_id, deal_ref),
    UNIQUE(workspace_id, id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(stage IN ('watching', 'analyzing', 'pursuing', 'under_contract',
                    'closed', 'passed'))
);

CREATE INDEX IF NOT EXISTS idx_platform_saved_deals_stage
    ON medawarcre.platform_saved_deals(workspace_id, stage, updated_at);

CREATE TABLE IF NOT EXISTS medawarcre.platform_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    saved_deal_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    body text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(workspace_id, saved_deal_id)
        REFERENCES medawarcre.platform_saved_deals(workspace_id, id)
        ON DELETE CASCADE,
    FOREIGN KEY(author_user_id) REFERENCES medawarcre.platform_users(id)
);

CREATE INDEX IF NOT EXISTS idx_platform_notes_deal
    ON medawarcre.platform_notes(workspace_id, saved_deal_id, created_at);

CREATE TABLE IF NOT EXISTS medawarcre.platform_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    saved_deal_id bigint NOT NULL,
    closed bigint NOT NULL,
    purchase_price double precision,
    notes text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(workspace_id, saved_deal_id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(workspace_id, saved_deal_id)
        REFERENCES medawarcre.platform_saved_deals(workspace_id, id)
        ON DELETE CASCADE,
    CHECK(closed IN (0, 1)),
    CHECK(purchase_price IS NULL OR purchase_price > 0)
);

CREATE TABLE IF NOT EXISTS medawarcre.platform_consents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    user_id bigint NOT NULL,
    consent_type text NOT NULL,
    granted bigint NOT NULL,
    version text NOT NULL,
    created_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    CHECK(consent_type IN ('terms', 'privacy', 'marketing', 'data_processing')),
    CHECK(granted IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_platform_consents_user
    ON medawarcre.platform_consents(
        workspace_id, user_id, consent_type, created_at
    );

CREATE TABLE IF NOT EXISTS medawarcre.platform_integration_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    client_id bigint,
    event_type text NOT NULL,
    payload text NOT NULL DEFAULT '{}',
    created_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(client_id)
        REFERENCES medawarcre.platform_connected_clients(id)
);

CREATE INDEX IF NOT EXISTS idx_platform_integration_events_workspace
    ON medawarcre.platform_integration_events(
        workspace_id, event_type, created_at
    );

CREATE TABLE IF NOT EXISTS medawarcre.platform_privacy_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    user_id bigint NOT NULL,
    kind text NOT NULL,
    status text NOT NULL DEFAULT 'received',
    detail text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    CHECK(kind IN ('access', 'export', 'delete', 'correct')),
    CHECK(status IN ('received', 'in_progress', 'completed', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_platform_privacy_requests_workspace
    ON medawarcre.platform_privacy_requests(workspace_id, status, created_at);

-- platform_human_identities is declared identically by
-- src/cre_mcp/platform/schema.py:223 and
-- src/cre_mcp/platform/connection.py:239 (CREATE TABLE IF NOT EXISTS in both).
-- The definitions agree column for column; this is the single reconciled form.
CREATE TABLE IF NOT EXISTS medawarcre.platform_human_identities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    subject_hash text NOT NULL,
    user_id bigint NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(provider, subject_hash),
    UNIQUE(provider, user_id),
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_platform_human_identities_user
    ON medawarcre.platform_human_identities(user_id);

-- Same story: src/cre_mcp/platform/schema.py:237 and
-- src/cre_mcp/platform/connection.py:253 declare identical tables.
CREATE TABLE IF NOT EXISTS medawarcre.platform_browser_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash text NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    csrf_hash text NOT NULL,
    expires_at text NOT NULL,
    revoked_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_platform_browser_sessions_user
    ON medawarcre.platform_browser_sessions(user_id, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS medawarcre.platform_operator_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash text NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    csrf_hash text NOT NULL,
    expires_at text NOT NULL,
    revoked_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_platform_operator_sessions_user
    ON medawarcre.platform_operator_sessions(user_id, revoked_at, expires_at);

-- ---------------------------------------------------------------------------
-- OAuth authority (src/cre_mcp/platform/auth.py, oauth migrations 1 and 2)
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/auth.py:79
CREATE TABLE IF NOT EXISTS medawarcre.platform_oauth_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    client_id text NOT NULL UNIQUE,
    redirect_uris text NOT NULL,
    scopes text NOT NULL,
    active bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    CHECK(active IN (0,1))
);

-- src/cre_mcp/platform/auth.py:124, with refresh_family_expires_at already
-- present (oauth migration 2 only backfills it on legacy databases).
CREATE TABLE IF NOT EXISTS medawarcre.platform_oauth_sessions (
    session_id text PRIMARY KEY,
    workspace_id text NOT NULL,
    user_id bigint NOT NULL,
    client_id text NOT NULL,
    scopes text NOT NULL,
    audience text NOT NULL,
    resource text NOT NULL,
    authority_version bigint NOT NULL,
    access_hash text NOT NULL UNIQUE,
    refresh_hash text NOT NULL UNIQUE,
    access_expires_at text NOT NULL,
    refresh_expires_at text NOT NULL,
    refresh_family_expires_at text NOT NULL,
    revoked_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(public_id) ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    FOREIGN KEY(client_id)
        REFERENCES medawarcre.platform_oauth_clients(client_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_platform_oauth_sessions_identity
    ON medawarcre.platform_oauth_sessions(workspace_id, user_id, revoked_at);

-- src/cre_mcp/platform/auth.py:94
CREATE TABLE IF NOT EXISTS medawarcre.platform_oauth_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash text NOT NULL UNIQUE,
    workspace_id text NOT NULL,
    user_id bigint NOT NULL,
    client_id text NOT NULL,
    redirect_uri text NOT NULL,
    code_challenge text NOT NULL,
    code_challenge_method text NOT NULL,
    scopes text NOT NULL,
    audience text NOT NULL,
    resource text NOT NULL,
    authority_version bigint NOT NULL,
    expires_at text NOT NULL,
    consumed_at text,
    session_id text,
    created_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(public_id) ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    FOREIGN KEY(client_id)
        REFERENCES medawarcre.platform_oauth_clients(client_id)
        ON DELETE CASCADE,
    FOREIGN KEY(session_id)
        REFERENCES medawarcre.platform_oauth_sessions(session_id)
        ON DELETE SET NULL,
    CHECK(code_challenge_method='S256')
);

-- src/cre_mcp/platform/auth.py:157
CREATE TABLE IF NOT EXISTS medawarcre.platform_oauth_refresh_history (
    token_hash text PRIMARY KEY,
    session_id text NOT NULL,
    rotated_at text NOT NULL,
    FOREIGN KEY(session_id)
        REFERENCES medawarcre.platform_oauth_sessions(session_id)
        ON DELETE CASCADE
);

-- platform_oauth_authorization_requests is declared identically by
-- src/cre_mcp/platform/schema.py:265 and
-- src/cre_mcp/platform/connection.py:267.
CREATE TABLE IF NOT EXISTS medawarcre.platform_oauth_authorization_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_hash text NOT NULL UNIQUE,
    client_id text NOT NULL,
    redirect_uri text NOT NULL,
    state text NOT NULL,
    scopes text NOT NULL,
    code_challenge text NOT NULL,
    code_challenge_method text NOT NULL,
    audience text NOT NULL,
    resource text NOT NULL,
    expires_at text NOT NULL,
    consumed_at text,
    created_at text NOT NULL,
    FOREIGN KEY(client_id)
        REFERENCES medawarcre.platform_oauth_clients(client_id)
        ON DELETE CASCADE,
    CHECK(code_challenge_method = 'S256')
);

-- ---------------------------------------------------------------------------
-- Admin controls (src/cre_mcp/platform/schema.py, _admin_controls_v1)
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/schema.py:322 — INTEGER PRIMARY KEY without
-- AUTOINCREMENT: this is a plain bigint primary key that doubles as the FK to
-- platform_users, NOT an identity column.
CREATE TABLE IF NOT EXISTS medawarcre.platform_internal_admins (
    user_id bigint PRIMARY KEY,
    role text NOT NULL,
    active bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    CHECK(role IN ('platform_admin', 'support')),
    CHECK(active IN (0,1))
);

-- src/cre_mcp/platform/schema.py:336, with subject_user_id added by
-- entitlements migration 1 (src/cre_mcp/platform/entitlements.py:503).
CREATE TABLE IF NOT EXISTS medawarcre.platform_external_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    provider text NOT NULL,
    external_account_id text NOT NULL,
    metadata text NOT NULL DEFAULT '{}',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    subject_user_id bigint
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    UNIQUE(provider, external_account_id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(length(trim(provider)) > 0),
    CHECK(length(trim(external_account_id)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_platform_external_accounts_workspace
    ON medawarcre.platform_external_accounts(workspace_id, provider, id);

CREATE INDEX IF NOT EXISTS idx_platform_external_accounts_subject
    ON medawarcre.platform_external_accounts(
        workspace_id, subject_user_id, provider, id
    );

-- Append-only by trigger. The grant block at the bottom of this file gives
-- medawarcre_app SELECT and INSERT only; the triggers are the second layer.
CREATE TABLE IF NOT EXISTS medawarcre.platform_admin_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint NOT NULL,
    actor_role text NOT NULL,
    action text NOT NULL,
    workspace_id bigint,
    target_type text NOT NULL,
    target_id text NOT NULL,
    reason_code text NOT NULL,
    reason text NOT NULL,
    before_json text NOT NULL,
    after_json text NOT NULL,
    created_at text NOT NULL,
    FOREIGN KEY(actor_user_id) REFERENCES medawarcre.platform_users(id),
    CHECK(actor_role IN ('platform_admin', 'support')),
    CHECK(reason_code IN ('initial_provisioning', 'customer_request',
                          'billing_correction', 'entitlement_correction',
                          'security_response', 'support_resolution',
                          'data_correction')),
    CHECK(length(trim(reason)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_platform_admin_audit_workspace
    ON medawarcre.platform_admin_audit(workspace_id, created_at, id);

-- ---------------------------------------------------------------------------
-- Skool lifecycle (src/cre_mcp/platform/schema.py, _skool_lifecycle_v1)
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/schema.py:409
CREATE TABLE IF NOT EXISTS medawarcre.platform_skool_join_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    subject_user_id bigint NOT NULL,
    community_id text NOT NULL,
    level_id text NOT NULL,
    state text NOT NULL,
    requested_by bigint NOT NULL,
    completed_by bigint,
    completion_source text,
    external_mapping_id bigint,
    completed_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(subject_user_id)
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    FOREIGN KEY(requested_by) REFERENCES medawarcre.platform_users(id),
    FOREIGN KEY(completed_by) REFERENCES medawarcre.platform_users(id),
    FOREIGN KEY(external_mapping_id)
        REFERENCES medawarcre.platform_external_accounts(id),
    CHECK(state IN ('pending','completed','canceled')),
    CHECK(completion_source IS NULL OR completion_source IN (
        'manual_admin_invite','zapier_invite'
    )),
    CHECK(length(trim(community_id)) > 0),
    CHECK(length(trim(level_id)) > 0)
);

-- Partial unique index: at most one pending join task per
-- (workspace, subject, community, level). Valid PostgreSQL, kept verbatim.
CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_skool_join_tasks_pending
    ON medawarcre.platform_skool_join_tasks(
        workspace_id, subject_user_id, community_id, level_id
    )
    WHERE state='pending';

CREATE INDEX IF NOT EXISTS idx_platform_skool_join_tasks_workspace
    ON medawarcre.platform_skool_join_tasks(
        workspace_id, state, created_at, id
    );

-- src/cre_mcp/platform/schema.py:458
CREATE TABLE IF NOT EXISTS medawarcre.platform_skool_reconciliations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    community_id text NOT NULL,
    artifact_hash text NOT NULL UNIQUE,
    source text NOT NULL,
    observed_at text NOT NULL,
    confidence text NOT NULL,
    complete bigint NOT NULL,
    certainty text NOT NULL,
    reason_code text NOT NULL,
    member_count bigint NOT NULL,
    mapped_member_count bigint NOT NULL,
    discrepancy_count bigint NOT NULL,
    conflict_count bigint NOT NULL,
    created_by bigint NOT NULL,
    created_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY(created_by) REFERENCES medawarcre.platform_users(id),
    CHECK(source IN ('operator_members_review')),
    CHECK(confidence IN ('confirmed','provisional','unverified')),
    CHECK(complete IN (0,1)),
    CHECK(certainty IN ('confirmed','uncertain','conflict')),
    CHECK(member_count >= 0),
    CHECK(mapped_member_count >= 0),
    CHECK(discrepancy_count >= 0),
    CHECK(conflict_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_platform_skool_reconciliations_workspace
    ON medawarcre.platform_skool_reconciliations(
        workspace_id, community_id, observed_at, id
    );

-- ---------------------------------------------------------------------------
-- Entitlements (src/cre_mcp/platform/entitlements.py)
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/entitlements.py:226 — INTEGER PRIMARY KEY without
-- AUTOINCREMENT; the workspace supplies the key, so no identity column.
CREATE TABLE IF NOT EXISTS medawarcre.platform_accounts (
    workspace_id bigint PRIMARY KEY,
    state text NOT NULL DEFAULT 'registered',
    reason text,
    updated_at text NOT NULL,
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(state IN ('invited', 'registered', 'verified', 'active', 'past_due',
                    'grace_period', 'suspended', 'under_review', 'canceled',
                    'deletion_pending', 'deleted'))
);

-- src/cre_mcp/platform/entitlements.py:235, with last_event_at added by
-- entitlements migration 1 (src/cre_mcp/platform/entitlements.py:310).
CREATE TABLE IF NOT EXISTS medawarcre.platform_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    provider text NOT NULL,
    external_subscription_id text NOT NULL,
    external_customer_id text,
    status text NOT NULL,
    plan_key text NOT NULL,
    current_period_end text,
    last_event_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(provider, external_subscription_id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(provider IN ('stripe', 'skool')),
    CHECK(status IN ('trialing', 'active', 'past_due', 'grace_period',
                     'paused', 'canceled', 'unpaid'))
);

CREATE INDEX IF NOT EXISTS idx_platform_subscriptions_workspace
    ON medawarcre.platform_subscriptions(workspace_id, provider, status);

-- src/cre_mcp/platform/entitlements.py:255, with subject_user_id
-- (entitlements.py:488) and scope (entitlements.py:870) added by later
-- migrations.
CREATE TABLE IF NOT EXISTS medawarcre.platform_access_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint NOT NULL,
    source text NOT NULL,
    external_ref text NOT NULL,
    profile text NOT NULL,
    plan_key text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    starts_at text NOT NULL,
    ends_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    subject_user_id bigint
        REFERENCES medawarcre.platform_users(id) ON DELETE CASCADE,
    scope text,
    UNIQUE(source, external_ref),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(source IN ('stripe', 'skool', 'manual', 'jv', 'promotion')),
    CHECK(profile IN ('local_scout', 'national_scout', 'full_operator',
                      'jv_partner')),
    CHECK(status IN ('pending', 'active', 'overridden', 'expiring', 'expired',
                     'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_platform_grants_workspace
    ON medawarcre.platform_access_grants(workspace_id, status, ends_at);

CREATE INDEX IF NOT EXISTS idx_platform_provider_grants_subject
    ON medawarcre.platform_access_grants(
        workspace_id, subject_user_id, source, status, ends_at
    );

CREATE INDEX IF NOT EXISTS idx_platform_grants_scope_subject
    ON medawarcre.platform_access_grants(
        workspace_id, scope, subject_user_id, status, ends_at
    );

-- src/cre_mcp/platform/entitlements.py:385 (the rebuilt table from
-- entitlements migration 1) plus every column added by provider-sync
-- migrations 1-5: object_stream_hash, restrictive_rank, canonical_action,
-- external_account_hash, bound_subject_user_id, bound_scope,
-- entitlement_input_hash, bound_plan_key, bound_profile.
CREATE TABLE IF NOT EXISTS medawarcre.platform_provider_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id bigint,
    provider text NOT NULL,
    event_id text NOT NULL,
    event_type text NOT NULL,
    payload text NOT NULL DEFAULT '{}',
    normalized_data text NOT NULL DEFAULT '{}',
    occurred_at text NOT NULL,
    outcome text NOT NULL DEFAULT 'received',
    reason_code text,
    duplicate_count bigint NOT NULL DEFAULT 0,
    replayed_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    object_stream_hash text,
    restrictive_rank bigint NOT NULL DEFAULT 0,
    canonical_action text,
    external_account_hash text,
    bound_subject_user_id bigint REFERENCES medawarcre.platform_users(id),
    bound_scope text,
    entitlement_input_hash text,
    bound_plan_key text,
    bound_profile text,
    UNIQUE(provider, event_id),
    FOREIGN KEY(workspace_id)
        REFERENCES medawarcre.platform_workspaces(id) ON DELETE CASCADE,
    CHECK(provider IN ('stripe', 'skool')),
    CHECK(outcome IN ('received', 'applied', 'duplicate', 'stale',
                      'quarantined', 'rejected', 'unmapped', 'malformed',
                      'failure', 'reconciled')),
    CHECK(duplicate_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_platform_provider_events_workspace
    ON medawarcre.platform_provider_events(
        workspace_id, provider, created_at, id
    );

CREATE INDEX IF NOT EXISTS idx_platform_provider_events_quarantine
    ON medawarcre.platform_provider_events(provider, outcome, id);

CREATE INDEX IF NOT EXISTS idx_platform_provider_event_stream_order
    ON medawarcre.platform_provider_events(
        provider, object_stream_hash, occurred_at DESC,
        restrictive_rank DESC, id DESC
    );

-- src/cre_mcp/platform/entitlements.py:459
CREATE TABLE IF NOT EXISTS medawarcre.platform_provider_event_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id bigint NOT NULL,
    outcome text NOT NULL,
    reason_code text,
    created_at text NOT NULL,
    FOREIGN KEY(provider_event_id)
        REFERENCES medawarcre.platform_provider_events(id) ON DELETE CASCADE,
    CHECK(outcome IN ('received', 'applied', 'duplicate', 'stale',
                      'quarantined', 'rejected', 'unmapped', 'malformed',
                      'failure', 'reconciled'))
);

CREATE INDEX IF NOT EXISTS idx_platform_provider_event_attempts_event
    ON medawarcre.platform_provider_event_attempts(provider_event_id, id);

-- ---------------------------------------------------------------------------
-- Triggers
--
-- SQLite raises sqlite3.IntegrityError for RAISE(ABORT, ...) inside a
-- constraint trigger, and the Python stores catch exactly that. Every function
-- below raises with ERRCODE 'check_violation' so psycopg surfaces
-- psycopg.errors.CheckViolation (an IntegrityError subclass) and the existing
-- except-clauses keep working unchanged. Message text is preserved verbatim.
-- ---------------------------------------------------------------------------

-- src/cre_mcp/platform/schema.py:388 and :397 — platform_admin_audit is
-- append-only. Two SQLite triggers, one shared plpgsql function.
CREATE FUNCTION medawarcre.platform_admin_audit_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    RAISE EXCEPTION 'platform_admin_audit is append-only'
        USING ERRCODE = 'check_violation';
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_admin_audit_append_only()
    FROM PUBLIC;

CREATE TRIGGER platform_admin_audit_no_update
BEFORE UPDATE ON medawarcre.platform_admin_audit
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_admin_audit_append_only();

CREATE TRIGGER platform_admin_audit_no_delete
BEFORE DELETE ON medawarcre.platform_admin_audit
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_admin_audit_append_only();

-- src/cre_mcp/platform/entitlements.py:1262 and :1271 — grant scope binding.
-- This carries real security semantics: it is what stops a provider grant from
-- being written without a subject, and what stops a subject grant from naming
-- a user who is not a member of the workspace it grants access to. The SQLite
-- form is a chain of SELECT CASE WHEN ... THEN RAISE(ABORT, ...) END; each one
-- becomes an IF ... THEN RAISE EXCEPTION ... END IF in the same order.
CREATE FUNCTION medawarcre.platform_grant_scope_binding()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.scope IS NULL
       OR NEW.scope NOT IN ('subject','workspace') THEN
        RAISE EXCEPTION 'grant scope is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.source IN ('stripe','skool','manual','promotion')
       AND (NEW.scope IS NULL OR NEW.scope <> 'subject') THEN
        RAISE EXCEPTION 'grant source requires subject scope'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.scope = 'workspace'
       AND (NEW.source <> 'jv' OR NEW.subject_user_id IS NOT NULL) THEN
        RAISE EXCEPTION 'workspace scope requires subjectless jv grant'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.scope = 'subject' AND NEW.subject_user_id IS NULL THEN
        RAISE EXCEPTION 'subject scope requires subject'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.scope = 'subject'
       AND NOT EXISTS (
           SELECT 1 FROM medawarcre.platform_memberships
           WHERE workspace_id = NEW.workspace_id
             AND user_id = NEW.subject_user_id
       ) THEN
        RAISE EXCEPTION 'grant subject is not a workspace member'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.source IN ('stripe','skool') AND NEW.ends_at IS NULL THEN
        RAISE EXCEPTION 'provider grant requires lease'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_grant_scope_binding() FROM PUBLIC;

CREATE TRIGGER platform_grant_scope_insert
BEFORE INSERT ON medawarcre.platform_access_grants
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_grant_scope_binding();

CREATE TRIGGER platform_grant_scope_update
BEFORE UPDATE ON medawarcre.platform_access_grants
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_grant_scope_binding();

-- src/cre_mcp/platform/entitlements.py:1280 — deleting a membership revokes
-- every live subject-scoped grant that membership carried. Without this, a
-- removed member keeps their entitlement. datetime('now') in SQLite yields
-- 'YYYY-MM-DD HH:MM:SS' in UTC; to_char(now() AT TIME ZONE 'UTC', ...)
-- reproduces that exact text format, which matters because these columns are
-- text, not timestamptz.
CREATE FUNCTION medawarcre.platform_subject_grants_membership_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
DECLARE
    sqlite_now text := to_char(now() AT TIME ZONE 'UTC',
                               'YYYY-MM-DD HH24:MI:SS');
BEGIN
    UPDATE medawarcre.platform_access_grants
       SET status = 'revoked',
           ends_at = COALESCE(ends_at, sqlite_now),
           updated_at = sqlite_now
     WHERE workspace_id = OLD.workspace_id
       AND subject_user_id = OLD.user_id
       AND scope = 'subject'
       AND status IN ('pending','active','overridden','expiring');
    RETURN OLD;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_subject_grants_membership_delete()
    FROM PUBLIC;

CREATE TRIGGER platform_subject_grants_membership_delete
BEFORE DELETE ON medawarcre.platform_memberships
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_subject_grants_membership_delete();

-- src/cre_mcp/platform/entitlements.py:783 and :802 — a stripe/skool external
-- account mapping must name a subject, and that subject must be a member of
-- the workspace the mapping is filed under. The SQLite triggers gate on
-- WHEN NEW.provider IN ('stripe','skool'); PostgreSQL keeps the same gate in a
-- WHEN clause (no subquery involved, so it is legal there).
CREATE FUNCTION medawarcre.platform_provider_mapping_subject_binding()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.subject_user_id IS NULL THEN
        RAISE EXCEPTION 'provider mapping requires subject'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM medawarcre.platform_memberships
        WHERE workspace_id = NEW.workspace_id
          AND user_id = NEW.subject_user_id
    ) THEN
        RAISE EXCEPTION 'provider subject is not a workspace member'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_provider_mapping_subject_binding()
    FROM PUBLIC;

CREATE TRIGGER platform_provider_mapping_subject_insert
BEFORE INSERT ON medawarcre.platform_external_accounts
FOR EACH ROW
WHEN (NEW.provider IN ('stripe','skool'))
EXECUTE FUNCTION medawarcre.platform_provider_mapping_subject_binding();

CREATE TRIGGER platform_provider_mapping_subject_update
BEFORE UPDATE OF workspace_id, subject_user_id, provider
ON medawarcre.platform_external_accounts
FOR EACH ROW
WHEN (NEW.provider IN ('stripe','skool'))
EXECUTE FUNCTION medawarcre.platform_provider_mapping_subject_binding();

-- src/cre_mcp/platform/entitlements.py:1592 and :1602 — provider receipt
-- binding validation, shared by the INSERT and UPDATE triggers. The SQLite
-- GLOB test ``x GLOB '*[^0-9a-f]*'`` asks "does x contain a character outside
-- 0-9a-f?"; the POSIX regex ``x ~ '[^0-9a-f]'`` asks exactly the same
-- question, case-sensitively, and is the faithful translation.
CREATE FUNCTION medawarcre.platform_provider_event_binding_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.canonical_action IS NOT NULL
       AND trim(NEW.canonical_action) = '' THEN
        RAISE EXCEPTION 'provider receipt action is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.external_account_hash IS NOT NULL
       AND (
           length(NEW.external_account_hash) <> 64
           OR NEW.external_account_hash ~ '[^0-9a-f]'
       ) THEN
        RAISE EXCEPTION 'provider receipt account hash is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.object_stream_hash IS NOT NULL
       AND (
           length(NEW.object_stream_hash) <> 64
           OR NEW.object_stream_hash ~ '[^0-9a-f]'
       ) THEN
        RAISE EXCEPTION 'provider receipt object hash is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF (NEW.bound_subject_user_id IS NULL) <> (NEW.bound_scope IS NULL) THEN
        RAISE EXCEPTION 'provider receipt authority is incomplete'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.bound_scope IS NOT NULL
       AND NEW.bound_scope NOT IN ('subject','workspace') THEN
        RAISE EXCEPTION 'provider receipt scope is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    -- A bound subject must be a member of the bound workspace.
    IF NEW.bound_subject_user_id IS NOT NULL
       AND (
           NEW.workspace_id IS NULL
           OR NOT EXISTS (
               SELECT 1 FROM medawarcre.platform_memberships
               WHERE workspace_id = NEW.workspace_id
                 AND user_id = NEW.bound_subject_user_id
           )
       ) THEN
        RAISE EXCEPTION 'provider receipt subject is not a member'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_provider_event_binding_insert()
    FROM PUBLIC;

CREATE TRIGGER platform_provider_event_binding_insert
BEFORE INSERT ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_provider_event_binding_insert();

-- src/cre_mcp/platform/entitlements.py:1602 — same shape checks, but the
-- membership re-check only fires when the binding is being established or
-- moved, not on every unrelated column update.
CREATE FUNCTION medawarcre.platform_provider_event_binding_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.canonical_action IS NOT NULL
       AND trim(NEW.canonical_action) = '' THEN
        RAISE EXCEPTION 'provider receipt action is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.external_account_hash IS NOT NULL
       AND (
           length(NEW.external_account_hash) <> 64
           OR NEW.external_account_hash ~ '[^0-9a-f]'
       ) THEN
        RAISE EXCEPTION 'provider receipt account hash is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.object_stream_hash IS NOT NULL
       AND (
           length(NEW.object_stream_hash) <> 64
           OR NEW.object_stream_hash ~ '[^0-9a-f]'
       ) THEN
        RAISE EXCEPTION 'provider receipt object hash is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF (NEW.bound_subject_user_id IS NULL) <> (NEW.bound_scope IS NULL) THEN
        RAISE EXCEPTION 'provider receipt authority is incomplete'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.bound_scope IS NOT NULL
       AND NEW.bound_scope NOT IN ('subject','workspace') THEN
        RAISE EXCEPTION 'provider receipt scope is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.bound_subject_user_id IS NOT NULL
       AND (
           OLD.workspace_id IS NULL
           OR OLD.bound_subject_user_id IS NULL
           OR OLD.bound_scope IS NULL
           OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id
           OR NEW.bound_subject_user_id
              IS DISTINCT FROM OLD.bound_subject_user_id
           OR NEW.bound_scope IS DISTINCT FROM OLD.bound_scope
       )
       AND (
           NEW.workspace_id IS NULL
           OR NOT EXISTS (
               SELECT 1 FROM medawarcre.platform_memberships
               WHERE workspace_id = NEW.workspace_id
                 AND user_id = NEW.bound_subject_user_id
           )
       ) THEN
        RAISE EXCEPTION 'provider receipt subject is not a member'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_provider_event_binding_update()
    FROM PUBLIC;

CREATE TRIGGER platform_provider_event_binding_update
BEFORE UPDATE ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_provider_event_binding_update();

-- src/cre_mcp/platform/entitlements.py:1612 — once a receipt's binding is
-- established it is immutable. The SQLite WHEN clause is a null-safe OR-chain
-- built on the ``IS NOT`` operator; PostgreSQL's null-safe equivalent is
-- ``IS DISTINCT FROM``. The whole condition moves into the function body so
-- there is no doubt about what fires when.
CREATE FUNCTION medawarcre.platform_provider_event_binding_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF (OLD.workspace_id IS NOT NULL
        AND NEW.workspace_id IS DISTINCT FROM OLD.workspace_id)
       OR NEW.provider IS DISTINCT FROM OLD.provider
       OR NEW.event_id IS DISTINCT FROM OLD.event_id
       OR NEW.event_type IS DISTINCT FROM OLD.event_type
       OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
       OR (OLD.canonical_action IS NOT NULL
           AND NEW.canonical_action IS DISTINCT FROM OLD.canonical_action)
       OR (OLD.external_account_hash IS NOT NULL
           AND NEW.external_account_hash
               IS DISTINCT FROM OLD.external_account_hash)
       OR (OLD.object_stream_hash IS NOT NULL
           AND NEW.object_stream_hash IS DISTINCT FROM OLD.object_stream_hash)
       OR (OLD.restrictive_rank IS NOT NULL
           AND NEW.restrictive_rank IS DISTINCT FROM OLD.restrictive_rank)
       OR (OLD.bound_subject_user_id IS NOT NULL
           AND NEW.bound_subject_user_id
               IS DISTINCT FROM OLD.bound_subject_user_id)
       OR (OLD.bound_scope IS NOT NULL
           AND NEW.bound_scope IS DISTINCT FROM OLD.bound_scope) THEN
        RAISE EXCEPTION 'provider receipt binding is immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION medawarcre.platform_provider_event_binding_immutable()
    FROM PUBLIC;

CREATE TRIGGER platform_provider_event_binding_immutable
BEFORE UPDATE ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_provider_event_binding_immutable();

-- src/cre_mcp/platform/entitlements.py:1795 and :1804 — entitlement target
-- binding validation. The hash is 'v1:' plus 64 lowercase hex characters, so
-- length 67 with a literal prefix; the GLOB->regex translation is the same as
-- above and applies to the substring after the prefix.
CREATE FUNCTION medawarcre.platform_provider_event_entitlement_binding()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.entitlement_input_hash IS NOT NULL
       AND (
           length(NEW.entitlement_input_hash) <> 67
           OR substr(NEW.entitlement_input_hash, 1, 3) <> 'v1:'
           OR substr(NEW.entitlement_input_hash, 4) ~ '[^0-9a-f]'
       ) THEN
        RAISE EXCEPTION 'provider receipt entitlement hash is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF (NEW.bound_plan_key IS NULL) <> (NEW.bound_profile IS NULL) THEN
        RAISE EXCEPTION 'provider receipt entitlement target is incomplete'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.bound_plan_key IS NOT NULL
       AND trim(NEW.bound_plan_key) = '' THEN
        RAISE EXCEPTION 'provider receipt plan binding is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.bound_profile IS NOT NULL
       AND NEW.bound_profile NOT IN ('local_scout', 'national_scout',
                                     'full_operator', 'jv_partner') THEN
        RAISE EXCEPTION 'provider receipt profile binding is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION
    medawarcre.platform_provider_event_entitlement_binding() FROM PUBLIC;

CREATE TRIGGER platform_provider_event_entitlement_binding_insert
BEFORE INSERT ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_provider_event_entitlement_binding();

CREATE TRIGGER platform_provider_event_entitlement_binding_update
BEFORE UPDATE ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION medawarcre.platform_provider_event_entitlement_binding();

-- src/cre_mcp/platform/entitlements.py:1813 — the entitlement input hash is
-- write-once, and a plan/profile target that was already set cannot be moved.
CREATE FUNCTION
    medawarcre.platform_provider_event_entitlement_binding_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF NEW.entitlement_input_hash IS DISTINCT FROM OLD.entitlement_input_hash
       OR (
           (
               OLD.bound_plan_key IS NOT NULL
               OR OLD.bound_profile IS NOT NULL
           )
           AND (
               NEW.bound_plan_key IS DISTINCT FROM OLD.bound_plan_key
               OR NEW.bound_profile IS DISTINCT FROM OLD.bound_profile
           )
       ) THEN
        RAISE EXCEPTION 'provider receipt entitlement binding is immutable'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION
    medawarcre.platform_provider_event_entitlement_binding_immutable()
    FROM PUBLIC;

CREATE TRIGGER platform_provider_event_entitlement_binding_immutable
BEFORE UPDATE ON medawarcre.platform_provider_events
FOR EACH ROW
EXECUTE FUNCTION
    medawarcre.platform_provider_event_entitlement_binding_immutable();

-- ---------------------------------------------------------------------------
-- Migration ledger seed
--
-- The SQLite migration runner in src/cre_mcp/platform/migrations.py decides
-- what to apply from MAX(version) per component. Seeding one row per component
-- at its highest version makes the runner see this schema as fully migrated,
-- so no SQLite migration callback tries to re-create or ALTER anything here.
-- Component names are the literals passed to apply_migrations(...) across the
-- platform package: schema.py:515/520, auth.py:304, entitlements.py:1900/1905.
-- ---------------------------------------------------------------------------

INSERT INTO medawarcre.platform_schema_versions
    (component, version, description, applied_at)
VALUES
    ('platform-core', 1, 'server-owned daily plan quotas',
     to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"')),
    ('admin-controls', 2, 'payload-free Skool join and current-state evidence',
     to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"')),
    ('oauth', 2, 'absolute refresh-token family lifetime',
     to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"')),
    ('entitlements', 1, 'provider event source ordering',
     to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"')),
    ('provider-sync', 5,
     'write-once entitlement input and target replay bindings',
     to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"+00:00"'))
ON CONFLICT (component, version) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Grants
--
-- The hosted application role has no default privileges in this schema —
-- migration 0001 revokes ALL on ALL TABLES from every role and hands out
-- privileges one relation at a time. Every platform_* table therefore needs an
-- explicit grant or the hosted process cannot read its own identity layer.
-- ---------------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON
    medawarcre.platform_schema_versions,
    medawarcre.platform_users,
    medawarcre.platform_plans,
    medawarcre.platform_workspaces,
    medawarcre.platform_memberships,
    medawarcre.platform_territories,
    medawarcre.platform_connected_clients,
    medawarcre.platform_saved_deals,
    medawarcre.platform_notes,
    medawarcre.platform_outcomes,
    medawarcre.platform_consents,
    medawarcre.platform_integration_events,
    medawarcre.platform_privacy_requests,
    medawarcre.platform_human_identities,
    medawarcre.platform_browser_sessions,
    medawarcre.platform_operator_sessions,
    medawarcre.platform_oauth_clients,
    medawarcre.platform_oauth_sessions,
    medawarcre.platform_oauth_codes,
    medawarcre.platform_oauth_refresh_history,
    medawarcre.platform_oauth_authorization_requests,
    medawarcre.platform_internal_admins,
    medawarcre.platform_external_accounts,
    medawarcre.platform_skool_join_tasks,
    medawarcre.platform_skool_reconciliations,
    medawarcre.platform_accounts,
    medawarcre.platform_subscriptions,
    medawarcre.platform_access_grants,
    medawarcre.platform_provider_events,
    medawarcre.platform_provider_event_attempts
TO medawarcre_app;

-- platform_admin_audit is append-only and is the only table here whose
-- triggers say so. The grant matches the trigger rather than relying on it:
-- no UPDATE, no DELETE, at any privilege level available to the app role.
GRANT SELECT, INSERT ON medawarcre.platform_admin_audit TO medawarcre_app;

-- Every platform_* identity column owns a sequence, and INSERT without a
-- sequence privilege fails. One statement covers all of them; migrations

-- Deliberately no sequence grant. These are IDENTITY columns, not `serial`:
-- PostgreSQL uses the backing sequence internally on INSERT and requires no
-- USAGE privilege on it, so a grant here buys nothing. It also costs: an
-- explicit ACL on an identity sequence is not reproduced by pg_dump/pg_restore,
-- so the restored catalog fingerprint stops matching the manifest and the
-- disaster-recovery verification fails. That is exactly how this line was
-- found -- by `test_native_dump_clean_restore_and_service_smoke`, not by review.
GRANT SELECT ON
    medawarcre.platform_schema_versions,
    medawarcre.platform_users,
    medawarcre.platform_plans,
    medawarcre.platform_workspaces,
    medawarcre.platform_memberships,
    medawarcre.platform_territories,
    medawarcre.platform_connected_clients,
    medawarcre.platform_saved_deals,
    medawarcre.platform_notes,
    medawarcre.platform_outcomes,
    medawarcre.platform_consents,
    medawarcre.platform_integration_events,
    medawarcre.platform_privacy_requests,
    medawarcre.platform_human_identities,
    medawarcre.platform_browser_sessions,
    medawarcre.platform_operator_sessions,
    medawarcre.platform_oauth_clients,
    medawarcre.platform_oauth_sessions,
    medawarcre.platform_oauth_codes,
    medawarcre.platform_oauth_refresh_history,
    medawarcre.platform_oauth_authorization_requests,
    medawarcre.platform_internal_admins,
    medawarcre.platform_external_accounts,
    medawarcre.platform_admin_audit,
    medawarcre.platform_skool_join_tasks,
    medawarcre.platform_skool_reconciliations,
    medawarcre.platform_accounts,
    medawarcre.platform_subscriptions,
    medawarcre.platform_access_grants,
    medawarcre.platform_provider_events,
    medawarcre.platform_provider_event_attempts
TO medawarcre_admin, medawarcre_backup;
