-- Phase 6A: the durable access-decision audit sink the hosted process needs
-- before it is allowed to serve a single tool call.
--
-- AccessMiddleware._record_audit calls AuditLog.record on the hosted path and
-- converts any failure into AUDIT_UNAVAILABLE, so a hosted process without a
-- working sink refuses work rather than proceeding unlogged. The file-backed
-- JSONL implementation cannot be that sink for a hosted process: it is local,
-- unreplicated, and lost with the container.
--
-- This is deliberately NOT medawarcre.access_decision_audit. That relation is
-- invocation-scoped and owned by PostgresAdmissionRepository: UNIQUE
-- (invocation_id, phase), phase IN ('admission','final'), and a uuid
-- workspace_id. The AuditLog interface has no invocation id, no phase, and its
-- workspace_id is the public identifier string ('ws_...'), not a uuid. Forcing
-- one onto the other would either violate the unique constraint or silently
-- drop rows, so this gets the smallest correct table of its own.

CREATE TABLE medawarcre.access_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The interface's own timestamp, kept as the text the caller produced so a
    -- record round-trips through AuditEvent unchanged.
    event_ts text NOT NULL CHECK (length(btrim(event_ts)) > 0),
    -- Server clock, which the caller cannot influence. When the two disagree,
    -- this is the one an investigation trusts.
    recorded_at timestamptz NOT NULL DEFAULT statement_timestamp(),
    workspace_public_id text NOT NULL CHECK (length(btrim(workspace_public_id)) > 0),
    tool text NOT NULL CHECK (length(btrim(tool)) > 0),
    decision text NOT NULL CHECK (length(btrim(decision)) > 0),
    reason text NOT NULL DEFAULT ''
);

CREATE INDEX access_audit_log_workspace_idx
    ON medawarcre.access_audit_log (workspace_public_id, id);

CREATE INDEX access_audit_log_recorded_idx
    ON medawarcre.access_audit_log (recorded_at, id);

-- Append-only in the database, not merely by convention in the application.
-- The application role below is granted no UPDATE or DELETE, and this trigger
-- is the second layer for any role that later acquires them.
CREATE FUNCTION medawarcre.access_audit_log_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    RAISE EXCEPTION 'medawarcre.access_audit_log is append-only'
        USING ERRCODE = 'check_violation';
END
$function$;

REVOKE ALL ON FUNCTION medawarcre.access_audit_log_append_only() FROM PUBLIC;

CREATE TRIGGER access_audit_log_no_update
BEFORE UPDATE ON medawarcre.access_audit_log
FOR EACH ROW EXECUTE FUNCTION medawarcre.access_audit_log_append_only();

CREATE TRIGGER access_audit_log_no_delete
BEFORE DELETE ON medawarcre.access_audit_log
FOR EACH ROW EXECUTE FUNCTION medawarcre.access_audit_log_append_only();

REVOKE ALL ON medawarcre.access_audit_log FROM PUBLIC;
GRANT SELECT, INSERT ON medawarcre.access_audit_log TO medawarcre_app;

-- Deliberately no sequence grant. These are IDENTITY columns, not `serial`:
-- PostgreSQL uses the backing sequence internally on INSERT and requires no
-- USAGE privilege on it, so a grant here buys nothing. It also costs: an
-- explicit ACL on an identity sequence is not reproduced by pg_dump/pg_restore,
-- so the restored catalog fingerprint stops matching the manifest and the
-- disaster-recovery verification fails. That is exactly how this line was
-- found -- by `test_native_dump_clean_restore_and_service_smoke`, not by review.
GRANT SELECT ON medawarcre.access_audit_log TO medawarcre_admin, medawarcre_backup;
