"""Pydantic data models for commercial real estate data."""

from cre_mcp.models.attributes import DealAttributes
from cre_mcp.models.capital import (
    CapitalDraft,
    CommitmentRecord,
    ComplianceCheck,
    InvestorRecord,
    InvestorRelationship,
    WaterfallResult,
    WaterfallYear,
)
from cre_mcp.models.comps import CompsProviderResult, SaleComp, ValueEstimate
from cre_mcp.models.deals import Deal, DealContext
from cre_mcp.models.enrichment import ListingFacts, OwnerRecord, ParcelRecord
from cre_mcp.models.evaluation import CalibrationReport, GradeCalibration
from cre_mcp.models.execution import (
    BrokerContact,
    BusinessPrincipal,
    BuyerProfile,
    ContactInfo,
    CounterAdvice,
    ClosingPlan,
    ClosingStep,
    DDItem,
    DDPlan,
    DDStatus,
    DebtSizing,
    FinancingOption,
    LoiDraft,
    OfferRecommendation,
    OutreachDraft,
    QualificationGate,
    QualifyResult,
    RegisteredAgentContact,
)
from cre_mcp.models.geo import GeoLevel, GeoRef
from cre_mcp.models.listings import (
    AggregatedSearchResult,
    Listing,
    ListingRef,
    ListingType,
    MarketOverview,
    PropertyDetail,
    PropertySummary,
    PropertyType,
    SearchResult,
    SourceCapabilities,
)
from cre_mcp.models.market import (
    MarketPack,
    MetricSeries,
    MetricValue,
    RentComparable,
    RentComps,
)
from cre_mcp.models.ops import (
    OperatingItem,
    OperatingPlaybook,
    OpsCategory,
    OpsStatus,
)
from cre_mcp.models.scoring import (
    Band,
    DealScore,
    DisqualifierSpec,
    Rubric,
    RubricResult,
    SignalResult,
    SignalSpec,
)
from cre_mcp.models.structure import (
    BootBasisResult,
    Exchange,
    ExchangeReplacement,
    StructureAdvice,
    StructureIntent,
)
from cre_mcp.models.tax import AfterTaxResult, DepreciationYear
from cre_mcp.models.underwriting import UnderwritingResult

__all__ = [
    "AggregatedSearchResult",
    "AfterTaxResult",
    "Band",
    "BootBasisResult",
    "BrokerContact",
    "BusinessPrincipal",
    "BuyerProfile",
    "CapitalDraft",
    "CalibrationReport",
    "CommitmentRecord",
    "ComplianceCheck",
    "CompsProviderResult",
    "ContactInfo",
    "CounterAdvice",
    "ClosingPlan",
    "ClosingStep",
    "DDItem",
    "DDPlan",
    "DDStatus",
    "DebtSizing",
    "DepreciationYear",
    "Deal",
    "DealAttributes",
    "DealContext",
    "DealScore",
    "DisqualifierSpec",
    "GeoLevel",
    "GeoRef",
    "GradeCalibration",
    "FinancingOption",
    "Exchange",
    "ExchangeReplacement",
    "Listing",
    "ListingFacts",
    "ListingRef",
    "ListingType",
    "LoiDraft",
    "InvestorRecord",
    "InvestorRelationship",
    "MarketOverview",
    "MarketPack",
    "MetricSeries",
    "MetricValue",
    "OwnerRecord",
    "OfferRecommendation",
    "OperatingItem",
    "OperatingPlaybook",
    "OpsCategory",
    "OpsStatus",
    "OutreachDraft",
    "ParcelRecord",
    "PropertyDetail",
    "PropertySummary",
    "PropertyType",
    "QualificationGate",
    "QualifyResult",
    "RentComparable",
    "RentComps",
    "RegisteredAgentContact",
    "Rubric",
    "RubricResult",
    "SearchResult",
    "SaleComp",
    "SourceCapabilities",
    "StructureAdvice",
    "StructureIntent",
    "SignalResult",
    "SignalSpec",
    "UnderwritingResult",
    "ValueEstimate",
    "WaterfallResult",
    "WaterfallYear",
]
