"""Multi-tenant platform foundation: auth, storage, and typed records."""

from cre_mcp.platform.auth import (
    AuthenticatedSession,
    ClientRegistration,
    OAuthSessionStore,
    SessionTokens,
)
from cre_mcp.platform.entitlements import (
    ACCOUNT_STATES,
    GRANT_SOURCES,
    GRANT_STATUSES,
    PROVIDERS,
    SUBSCRIPTION_STATUSES,
    AccessGrant,
    AccountRecord,
    EffectiveAccess,
    EntitlementStore,
    EventResult,
    ProviderEvent,
    SubscriptionRecord,
)
from cre_mcp.platform.models import (
    CLIENT_STATUSES,
    CONSENT_TYPES,
    MEMBERSHIP_ROLES,
    PRIVACY_REQUEST_KINDS,
    PRIVACY_REQUEST_STATUSES,
    PRIVACY_REQUEST_TRANSITIONS,
    SAVED_DEAL_STAGES,
    ConnectedClient,
    ConsentRecord,
    IntegrationEvent,
    Membership,
    Note,
    Outcome,
    Plan,
    PrivacyRequest,
    SavedDeal,
    Territory,
    User,
    Workspace,
)
from cre_mcp.platform.repository import PlatformRepository, get_platform_repository
from cre_mcp.platform.schema import PLATFORM_TABLES, create_schema

__all__ = [
    "AuthenticatedSession",
    "ACCOUNT_STATES",
    "GRANT_SOURCES",
    "GRANT_STATUSES",
    "PROVIDERS",
    "SUBSCRIPTION_STATUSES",
    "AccessGrant",
    "AccountRecord",
    "EffectiveAccess",
    "EntitlementStore",
    "EventResult",
    "ProviderEvent",
    "SubscriptionRecord",
    "CLIENT_STATUSES",
    "CONSENT_TYPES",
    "ClientRegistration",
    "ConnectedClient",
    "ConsentRecord",
    "IntegrationEvent",
    "MEMBERSHIP_ROLES",
    "Membership",
    "Note",
    "OAuthSessionStore",
    "Outcome",
    "PLATFORM_TABLES",
    "PRIVACY_REQUEST_KINDS",
    "PRIVACY_REQUEST_STATUSES",
    "PRIVACY_REQUEST_TRANSITIONS",
    "Plan",
    "PlatformRepository",
    "PrivacyRequest",
    "SAVED_DEAL_STAGES",
    "SavedDeal",
    "SessionTokens",
    "Territory",
    "User",
    "Workspace",
    "create_schema",
    "get_platform_repository",
]
